name: rides_showcase
description: Showcase app for ride booking
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  geocoding: ^3.0.0
  go_router: ^14.8.1
  google_maps_flutter: ^2.12.1
  intl: ^0.19.0
  json_serializable: ^6.9.4
  location: ^8.0.0
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0



flutter:
  uses-material-design: true
  generate: true
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Regular.ttf
          - asset: assets/fonts/Nunito-Bold.ttf
            weight: 700
          - asset: assets/fonts/Nunito-Italic.ttf
            style: italic
          - asset: assets/fonts/Nunito-Light.ttf
            weight: 300
          - asset: assets/fonts/Nunito-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/Nunito-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/Nunito-ExtraBold.ttf
            weight: 800
            style: italic

  assets:
    - assets/images/

platform:
  android:
    minSdkVersion: 21
  ios:
    deploymentTarget: 11.0
