name: rides_pr_workflow

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - develop

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      coverage_excludes: "**/*.g.dart"
      min_coverage: 75